name: Deploy

on:
  push:
    branches: main
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      BASE_URL: "mcut-course.com"
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Generate Pages
      run: npm run gen-prod
    - name: Sitemap
      run: node asset/utils/sitemap.js $BASE_URL
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
        force_orphan: true
        cname: ${{ env.BASE_URL }}